name: My First Workflow

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 🌎"

      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: List Files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:" 
          tree
      
